config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, { format: 'json' } do
    get "fetch_a_page_of_posts", to: "fetch_posts#fetch_a_page_of_posts"
    get "get_new_post", to: "get_new_post#get_new_post"
    get "get_post_image_url", to: "get_new_post#get_post_image_url"
  end
  
  namespace :admin do
    root to: 'index#index'
    resources :index, only: %i[index show]
  end
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'posts#index'

  resources :users do
    member do
      # フォロワー一覧のパス（余裕があったら追加する）
      #  get :following, :followers
    end
  end

  resources :posts do
    resources :post_likes, only: %i[create destroy]
    resources :comments do
      resources :comment_likes, only: %i[create destroy]
    end
  end
  resources :relationships, only: %i[create destroy]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :postlikes, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  validates :text, presence: true, length: { maximum: 140 }

  enum publishing_policy: { unlimited: 1, follower_limited: 2, self_limited: 3 }

  scope :my_posts, -> (user) {where(user_id: user.id)}

  def add_like(user)
    postlikes.create(user_id: user.id)
  end

  def delete_like(user)
    postlikes.find_by(user_id: user.id).destroy
  end

  def author?(post, user)
    user.id == post.user_id
  end

  def logged_in_user_feed_posts(user)
    following_posts = user.fetch_following_user_posts
    Post.my_posts(user).or(following_posts).order(created_at: :desc)
  end

  def unlogged_in_user_feed_posts
    Post.where(publishing_policy: :unlimited).order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true
require "post.rb"

class PostsController < ApplicationController
  before_action :check_user_login, only: %i[new edit delete]
  def index
    if current_user
      @posts = Post.new().logged_in_user_feed_posts(current_user).page(params[:page]).includes(:user, :images)
      @post = Post.new
      Post::IMAGE_MAX_LENGTH.times { @post.images.build }
    else
      @posts = Post.new().unlogged_in_user_feed_posts.page(params[:page])
    end
  end

  def show
    if current_user
      @post = Post.new().logged_in_user_feed_posts(current_user).find(params[:id])
      @comments = @post.comments
    else
      @post = Post.where(publishing_policy: :unlimited).find(params[:id])
      @comments = @post.comments
    end
  end

  def new
    @post = Post.new
    Post::IMAGE_MAX_LENGTH.times { @post.images.build }
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      render json: @post, status: 200
    else
      @errors = @post.errors.full_messages
      render json: @errors, status: 422
    end
  end

  def edit
    @post = Post.find(params[:id])
    Post::IMAGE_MAX_LENGTH.times { @post.images.build }
    unless @post.author?(@post, current_user)
      redirect_to post_path(@post)
      flash[:alert] = '編集、削除の権限はありません'
    end
  end

  def update
    @post = Post.find(params[:id])
    unless @post.author?(@post, current_user)
      redirect_to post_path(@post)
      flash[:alert] = '編集、削除の権限はありません'
    end
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    unless post.author?(post, current_user)
      flash[:alert] = '編集、削除の権限はありません'
      return redirect_to post_path(post)
    end
    post.destroy
    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(
      :text,
      :publishing_policy,
      :created_at,
      :updated_at,
      images_attributes: %i[image id]
    ).merge(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post, data: { remote: true }, :html => {:class => "post-create"}) do |f| %>
  <div class="card m-2" style="width: 50%; min-height: 250px; position:relative; left: 25%; background-color: #FFECF9;">
      <div class="card-body">
        <div class="field m-2">
          <%= f.text_field :text, :class => 'text_input',placeholder: "いまどうしてる？"%>
        </div>
          <div class="field">
        <%= f.fields_for :images do |image_form| %>
            <%= image_form.file_field :image, style: "margin-bottom: 2px;" %>
        <% end %>
          <%= f.label :publishing_policy %>
          <%= f.select :publishing_policy, Post.publishing_policies.keys,{selected: 'unlimited'} %>
          </div>
        <div class="actions">
          <%= f.submit '投稿する' %>
        </div>
      </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>投稿を編集</h1>
<%= render 'form', post: @post %>
<%= link_to '投稿詳細', @post %>
<%= link_to 'ホームへ戻る', posts_path %>

app/views/posts/index.html.erb
<% if current_user %>
  <div>
    <%= render 'form', post: @post %>
  </div>
  <div id="new_post"></div>
<% end %>
<% @posts.each do |post| %>
  <div class="card m-2" style="width: 50%; min-height: 250px; position:relative; left: 25%;">
    <div class="card-body">
      <div class="row" style="padding: 0 16px;">
        <div class="col-md-10">
          <strong class="card-title mb-2">
            <%= link_to user_path(post.user) do %>
              <%= post.user.name %>
            <% end %>
          </strong>
        </div>
        <div class="col-md-2">
          <%= link_to(post_path(post)) do %>
            <button type="button" class="btn btn-light" style="font-size: 10px;">詳細</button>
          <% end %>
        </div>
      </div>
      <% post.images.each do |image| %>
        <%= image_tag(image.image_url(:small)) %>
      <% end %>
      <div class="card-text p-3 mt-1 bg-light" style="min-height: 180px;" id="post_text"><%= post.text %></div>
    </div>
  </div>
<% end %>
<div id="posts"></div>
<div style="text-align: center;">
  <%= link_to "次のページを読み込む", api_fetch_a_page_of_posts_path, {id: "next", remote: true} %>
</div>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render 'form', post: @post %>
<%= link_to 'ホームへ戻る', posts_path %>

app/views/posts/show.html.erb
<div id="post_show_page" style="height: 100vh;">
  <div class="card m-2" style="width: 50%; min-height: 250px; position:relative; left: 25%;">
    <div class="card-body">
      <div style="padding: 0 16px;">
        <strong class="card-title mb-2">
          <%= link_to user_path(@post.user) do %>
            <%= @post.user.name %>
          <% end %>
        </strong>
      </div>
      <% @post.images.each do |image| %>
        <%= image_tag(image.image_url(:medium)) %>
      <% end %>
      <div class="card-text p-3 mt-1 bg-light" style="min-height: 180px;">
        <%= @post.text %>
        <div style="float: right;">
          <% if @post.postlikes.present? %>
            <%= button_to 'いいねを取り消す', post_post_like_path(@post), method: :delete %>
          <% else %>
            <%= button_to 'いいね', post_post_likes_path(@post), method: :post %>
          <% end %>
          <% if current_user %>
            <% if @post.user_id == current_user.id %>
              <%= link_to '編集', edit_post_path(@post) %>
              <%= link_to '削除', @post, method: :delete, data: { confirm: '本当に削除しますか？' } %>
            <% end %>
          <% end %>
        </div>
      </div>
      <% @comments.each do |comment| %>
        <div class="card-text p-3 mt-1" style="min-height: 50px; background-color: #FAFAF8;">
          <%= link_to user_path(comment.user) do %>
            <%= comment.user.name %>
          <% end %>
          <br/>
          <%= comment.text %>
          <span style="float: right; position: relative; bottom: 20px;">
            <% if comment.commentlikes.present? %>
              <%= button_to 'いいねを取り消す', post_comment_comment_like_path(@post, comment), method: :delete %>
            <% else %>
              <%= button_to 'いいね', post_comment_comment_likes_path(@post, comment), method: :post %>
            <% end %>
            <% if current_user %>
              <% if comment.user_id == current_user.id %>
                <%= link_to '編集', edit_post_comment_path(@post, comment) %>
                <%= link_to '削除', post_comment_path(@post, comment), method: :delete, data: { confirm: '本当に削除しますか？' } %>
              <% end %>
            <% end %>
          </span>
        </div>
      <% end %>
      <div style=" margin-top: 5px;">
        <% if current_user %>
          <%= link_to 'コメントを追加', new_post_comment_path(@post) %>
        <% end %>
      </div>
    </div>
  </div>
  <span style="float: right;">
    <%= link_to 'ホームへ戻る', posts_path %>
  </span>
</div>